attention
I wrote it but failed to run as the phrase said:
                                                                          Traceback (most recent call last):
                                                                                 u=UserInfo("admin","123456");
                                                                          TypeError: object() takes no parameters
However, I found it is because I only wrote one underline to surround the "init",which is wrong.
Correction: 
                      class UserInfo:
                           def __init__(self,name,pwd):
                               self.username= name
                               self._pwd= pwd
                           def output (self):
                               print("用户："+self.username +"\n密码："+self._pwd);
                      u=UserInfo("admin","123456");
                      u.output()